### ISSUE TITLE
Inheritance issue

### ISSUE THREAD

**Issue by ericv889** [runxc1/MicroRuleEngine#10]
First of all I would like to say you have done a wonderful job. This project is very nice. However, I encountered a small problem with inheritance. 

As soon as you add a subclass (let's say 'SpecialOrder' is a subclass of Order) and if you add a specific property to that subclass (let's say an integer, called 'SpecialId'), then the test fails on the following line, namely line 128 of MRE.cs: 
`propExpression = Expression.PropertyOrField(propExpression, childProperties[i]);`

As soon as the iterator reaches the second property, it returns the following message, because the property SpecialId isn't a property of the base class Order:
**'SpecialId is not a member of MicroRuleEngine.Tests.Models.Order'**

Do you have any idea how to resolve this issue?
Thanks in advance.

**Comment by jamescurran** [comment]
As far as I can tell, you've written something like this:
`            var  order = this.GetSpecialOrder();
            Rule rule = new Rule() {MemberName = "SpecialId", TargetValue = "5", Operator = "Equal"};

            MRE engine = new MRE();
            var testit = engine.CompileRule<Order>(rule);
            bool passes = testit(order);
            Assert.IsTrue(passes);`

The solution is to change it to this:
`            var testit = engine.CompileRule<SpecialOrder>(rule);
`
