### ISSUE TITLE
Question on Json

### ISSUE THREAD

**Issue by ursg004** [runxc1/MicroRuleEngine#11]
is it possible to use the rule engine against a json document using json rule ?

**Comment by jamescurran** [comment]
I'm unclear about which you mean by a "json rule" (or a "json document" for that matter).

The object being testing must be a POCO object.  That could be a deserializer JSON object.

**Comment by runxc1** [comment]
As @jamescurran points out the Rule Engine works against C# objects so anything in JSON would have to be deserialized to a C# object.
