### ISSUE TITLE
To change operator from string to be enum

### ISSUE THREAD

**Issue by BggClr** [runxc1/MicroRuleEngine#14]
To avoid usage issues and for consistency it would be great if Operator property in the Rule should be enum rather than string

**Comment by jamescurran** [comment]
The original syntax uses strings and that was kept to maintain backward compatibility.  However, the newer Rule.Create() syntax uses the enum mreOperator.

**Comment by runxc1** [comment]
Changing the operator to an Enum as opposed to a string would remove critical functionality of the MRE.   There are overloads as noted by @jamescurran but the library also allows you to execute any boolean method on an object.
