### ISSUE TITLE
Apply rules on  XML and JSON objects

### ISSUE THREAD

**Issue by yesuvadian** [runxc1/MicroRuleEngine#17]
[MicroRuleEngine-master.zip](https://github.com/runxc1/MicroRuleEngine/files/3882230/MicroRuleEngine-master.zip)
Guys,

I have modified the rule engine to support applying rules on XML and JSON objects. Shall I go ahead and create a pull request?

The modified source is attached for your reference,

Thanks,
Yesu

**Comment by yesuvadian** [comment]
No longer needed I did fork the branch

**Comment by runxc1** [comment]
Sounds good, after forking if you check in a pull request with additional test cases to cover the new functionality it'll eventually get reviewed.

**Comment by Cloud33** [comment]
@yesuvadian @runxc1 
Excellent function. I think microrule engine can steal task data for calculation, which will be very good
