### ISSUE TITLE
How evaluate an Object in a collection ?

### ISSUE THREAD

**Issue by jperezmedina** [runxc1/MicroRuleEngine#5]
I rule example of how to use the MicroRuleEngine with a childProperty is included in the solution. For instance:

```
[TestMethod]
    public void ChildProperties()
    {
        Order order = this.GetOrder();
        Rule rule = new Rule()
        {
            MemberName = "Customer.Country.CountryCode",
            Operator = System.Linq.Expressions.ExpressionType.Equal.ToString("g"),
            TargetValue = "AUS"
        };
        MRE engine = new MRE();
        var compiledRule = engine.CompileRule<Order>(rule);
        bool passes = compiledRule(order);
        Assert.IsTrue(passes);
        order.Customer.Country.CountryCode = "USA";
        passes = compiledRule(order);
        Assert.IsFalse(passes);
    }
```

But, in my case, I need create a rule that evaluates is the cost of the Item with the ItemCode = "MM23" (so, the first Item object) is 'LessThanOrEqual' to 8.10M. How i can make it ?

**Comment by runxc1** [comment]
Do you have the ability to alter the Base Class?   Currently the MicroRuleEngine can execute a boolean method given an array of inputs, and there are a couple examples of that.

**Comment by jperezmedina** [comment]
I'm new with C#. Could you detail more about it? How alter the base Class
to support collection[0].feature? Where are the examples? Thanks

**Comment by jamescurran** [comment]
I've added this feature to my fork (https://github.com/jamescurran/MicroRuleEngine).  Using the new syntax, it would be:  

            Rule rule = Rule.Create("Items[0].Cost", mreOperator.LessThanOrEqual, 8.10m);

**Comment by fschaal** [comment]
@jamescurran , would you also be able to use the link method All / Any on a collection?

**Comment by jamescurran** [comment]
So, basically, you'd want it to be the equivalent of "Items.All(i=>i.Status == Shipped)" ?

**Comment by jamescurran** [comment]
Actually, this should work for that (I'd forgotten about it)

            Rule rule = Rule.All("Items", Rule.Create("Status", mreOperator.Equal, "Shipped"));

**Comment by runxc1** [comment]
The changes from @jamescurran enabling this have been pulled in so this is now possible.
