### ISSUE TITLE
Target member values?

### ISSUE THREAD

**Issue by benfoster** [runxc1/MicroRuleEngine#6]
Would it be possible to produce a binary expression based on a member property rather than a fixed value? For example:

```
            var rule = new Rule 
            {
                MemberName = "Customer.Phone",
                Operator = ExpressionType.Equal.ToString("g"),
                TargetValue = "Customer.Mobile"
            };
```

This checks if the value of the `Customer.Phone` property equals `Customer.Mobile` property.

**Comment by runxc1** [comment]
So you would have to add that functionality but I don't imagine that it would be too hard.   If you look at line 139-161 in
https://github.com/runxc1/MicroRuleEngine/blob/master/MicroRuleEngine/MRE.cs

You can see how it is parsing the Expression and even how the "IsMatch" Regex functionality is added.  It would be fairly straight forward to put a mechanism in where if the Operator starts with "Self." that it then parses both the MemberName and the TargetValue to create a binary expression

**Comment by jamescurran** [comment]
I've added that functionality (and a few others -- and a more concise syntax), in my fork of this.
Your example would be written as:

    Rule rule = Rule.Create("Customer.Phone", mreOperator.Equal, "*.Customer.Mobile");

https://github.com/jamescurran/MicroRuleEngine
(in addition to my own changes, I tried to incorporate every other fork I could find)

**Comment by runxc1** [comment]
The changes from @jamescurran enabling this have been pulled in so this is now possible.
