### ISSUE TITLE
UI for this project

### ISSUE THREAD

**Issue by schalla27** [runxc1/MicroRuleEngine#7]
First off all, I greatly appreciate your effort and data binding the output  can be doable
Just have a couple of questions:
In your Example usage you have  order.Customer.FirstName = "Philip" after the test executes. 
1) Can we data bind the output so that it can update the UI? 
For example: lets say the Rule passes then show a checkbox else hide the checkbox. 
2) Can we create a UI for adding new rules? This is like the ruleset editor in Windows Workflow. All I am trying to do is build a UI where the admin can set up their rules based on some classes and these rules will be evaluated on the fly. 
3) How do we save these rules to the DB?

**Comment by runxc1** [comment]
So I originally built this for some work I was doing at a company that I left 6ish years ago so I haven't really used it myself in some time.   At the time all of the rules were saved as Xml documents but there are a lot of ways you could save the Rules out.

As for UI concerns that would depend upon the UI.  I had built a specialized Asp.net MVC UI that built up the rules but all the object properties were known ahead of time.  Lots of ways you could use the Library but the UI concerns are more outside of the scope of the library.

**Comment by schalla27** [comment]
Ok thank you.
6 years was a long time.. but any links or articles which have helped you?

**Comment by anandtpatel** [comment]
I have built really fancy UI using vuejs. This was huge help to get that successfully done.

**Comment by runxc1** [comment]
@anandtpatel  that is cool to hear

**Comment by anandtpatel** [comment]
I just added support for collection parameters to build rule on them

**Comment by runxc1** [comment]
@anandtpatel I just found a need for this and built out a Vuejs UI as well and have added methods to inspect a Type and find all of the Fields and Operators that you can use with each field that makes creating a UI a lot easier.  A UI is still outside of the scope of this project but if I get a chance I might be able to extract part of the UI and put a demo up as it helps in visualizing your rules.
