### ISSUE TITLE
Nullable<Int32> HasValue ?

### ISSUE THREAD

**Issue by marcoprotano** [runxc1/MicroRuleEngine#9]
![image](https://user-images.githubusercontent.com/29278864/26929330-85d27562-4c59-11e7-9085-d9b16bac04a4.png)

Hi Bret, I'm working on Nullable<Int32> as you can see on attached image. I would like to know if there is a better approach to check if a nullable prop has a value or not.

Thanks in advance

Marco

**Comment by jamescurran** [comment]
I just tested that on my fork (https://github.com/jamescurran/MicroRuleEngine) and the simple Rule seems to work:

            Rule rule = Rule.Create("MyNullableProp", mreOperator.Equals, 21);

Is True if MyNullableProp is 21, and false if it's null or has a non-21 value.

Alternately, you can use the rule:

            Rule rule = Rule.Create("MyNullableProp", mreOperator.NotEqual, null);
is True if MyNullableProp has a value. (I don't think I did anything specific to handle that --- it may have been part of one of the forks I incorporated into mine)

**Comment by runxc1** [comment]
I have pulled in the changes from @jamescurran so am closing this out.
